# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBookingItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBookingLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryInstruction', models.CharField(blank=True, max_length=2000, null=True)),
                ('itemsRequirePurchase', models.BooleanField(default=False)),
                ('pickupTime', models.DateField(blank=True, null=True)),
                ('customerFee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('customerReference', models.CharField(blank=True, max_length=50, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('taxInclusivePrice', models.NullBooleanField()),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('driverFeePercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('driverMatchCode', models.CharField(blank=True, max_length=200, null=True)),
                ('deliverySequence', models.IntegerField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=4000, null=True)),
                ('dropoffDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_detail', to='api.DeliveryBookingLocationModel')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryEventWebhookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraAddressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateProvince', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('suburbLocality', models.CharField(blank=True, max_length=35, null=True)),
                ('postcode', models.CharField(blank=True, max_length=11, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easliestTime', models.DateField(blank=True, null=True)),
                ('latestTime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliverybookingmodel',
            name='dropoffWindow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TimeFrameModel'),
        ),
        migrations.AddField(
            model_name='deliverybookingmodel',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeliveryBookingItemModel'),
        ),
        migrations.AddField(
            model_name='deliverybookingmodel',
            name='webhooks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeliveryEventWebhookModel'),
        ),
        migrations.AddField(
            model_name='deliverybookinglocationmodel',
            name='additionnalAdressDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ExtraAddressDetails'),
        ),
    ]
